
set(target "appPharmaToolsApp")
set(working_dir "/Users/vincent/dev/pharmatools/app")
set(src_and_dest_list
    "/Users/vincent/dev/pharmatools/app/qml/Please.js"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/qml/Please.js"
    "/Users/vincent/dev/pharmatools/app/qml/inventory.json"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/qml/inventory.json"
    "/Users/vincent/dev/pharmatools/app/qml/sorties.json"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/qml/sorties.json"
    "/Users/vincent/dev/pharmatools/app/fonts/Montserrat-VariableFont_wght.ttf"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/fonts/Montserrat-VariableFont_wght.ttf"
    "/Users/vincent/dev/pharmatools/app/fonts/PTSansNarrow-Regular.ttf"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/fonts/PTSansNarrow-Regular.ttf"
    "/Users/vincent/dev/pharmatools/app/fonts/RobotoMono-VariableFont_wght.ttf"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/fonts/RobotoMono-VariableFont_wght.ttf"
    "/Users/vincent/dev/pharmatools/app/icons/ico_beaker.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_beaker.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_box_in.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_box_in.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_box_out.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_box_out.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_cart.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_cart.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_check.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_check.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_cross.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_cross.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_cueillette.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_cueillette.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_edit_stock.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_edit_stock.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_filter.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_filter.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_hourglass.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_hourglass.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_inout.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_inout.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_inventory.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_inventory.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_label.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_label.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_order.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_order.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_plus.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_plus.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_print.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_print.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_search.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_search.svg"
    "/Users/vincent/dev/pharmatools/app/icons/ico_warning.svg"
    "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/PharmaToolsApp/icons/ico_warning.svg"

)
set(timestamp_file "/Users/vincent/dev/pharmatools/app/PharmaToolsApp/build/WebAssembly_Qt_6_9_0_multi_threaded-Release/.qt/appPharmaToolsApp_res.txt")
